title: Navio Pirata
email: rita.cassia.barbosa.farias@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Ciência de Dados e Educação.

theme: minima

base_url: "" # the subpath of your site, e.g. /blog

url: "https://r-it-a.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: R-it-a

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/sobre.md
  - _pages/arquivo.md

include:
    - _pages

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
